3-module
js-tasks-ru/jsbasic-20240520_daria-kolenchenko pull request #4
Opened 2024-05-28 09:21 UTC by Dariechka

2024-05-28 09:21 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-05-30 16:23 UTC, SinimaWath requested changes

2024-05-30 16:23 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  .map((item, index, arr) => (index === arr.length -1) ? item.name + ', ' + item.balance :  item.name + ', ' + item.balance + '\n')
Давай, добавлять перенос строки через метод join:
```
users.filter().map().join('\n')
```

2024-05-30 16:23 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return {min, max};
Тут не нужны особо временные переменные:
```
return {
  min: arr[0],
  max: arr[arr.length - 1]
}
```

2024-05-30 18:59 UTC, Dariechka commented on 3-module/4-task/index.js
> +  .map((item, index, arr) => (index === arr.length -1) ? item.name + ', ' + item.balance :  item.name + ', ' + item.balance + '\n')
исправила

2024-05-30 18:59 UTC, Dariechka commented on 3-module/5-task/index.js
> +  return {min, max};
заменила и удалило ненужное

2024-05-30 19:21 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-06-01 14:18 UTC, SinimaWath requested changes

2024-06-01 14:18 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      if (table.rows[i].cells[3].getAttribute('data-available') === 'true') {
data аттрибуты стоит получать через специальное свойство:
`dataset.available`

2024-06-02 09:12 UTC, Dariechka commented on 4-module/3-task/index.js
> +      if (table.rows[i].cells[3].getAttribute('data-available') === 'true') {
исправила

2024-06-02 09:14 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-06-03 18:37 UTC, SinimaWath approved these changes
Все круто!

2024-06-03 18:38 UTC, merged